### ISSUE TITLE
Consider using queue interprop as abstraction for queues

### ISSUE THREAD

**Issue by makasim** [dereuromark/cakephp-queue#160]
Hello!

Please look at https://github.com/queue-interop/queue-interop project. Using interfaces from it allows us reuse some implementations like enqueue, which supports a lot of transports. You can outsource some code

**Comment by dereuromark** [comment]
In light of https://github.com/dereuromark/cakephp-queue/pull/159, can you elaborate on what needs to change here etc?

**Comment by makasim** [comment]
The InteropQueueTransport could be introduced which is able to send emails to the queue interop compatible transport.

**Comment by dereuromark** [comment]
I see nothing for "transport" in https://github.com/queue-interop/queue-interop/tree/master/src etc.
Can you be a bit more verbose on what exactly needs changing in this queue?
And also, what the benefit for people would be? This one is specifically designed to not have any external dependencies, so that one should be "opt-in" as per those guidelines IMO.

**Comment by makasim** [comment]
by transport I meant something that implements queue interop interface https://github.com/queue-interop/queue-interop#implementations

**Comment by makasim** [comment]
> And also, what the benefit for people would be

This queue provides an easy to use implementation, though a developer has a chance to change it to something more sophisticated like AmazonSQS or RabbitMQ

**Comment by dereuromark** [comment]
I feel a bit like this is out of scope of this plugin. But I will leave it open for feedback from others.
