### ISSUE TITLE
Exception: Expected configuration key "Queue.exitwhennothingtodo" not found.

### ISSUE THREAD

**Issue by hectorviov** [dereuromark/cakephp-queue#198]
Everything was working fine, but after a "composer update" command I'm getting the title's exception when trying to run "bin/cake queue runworker". I added the "'exitwhennothingtodo' => false" on the app_queue.php config file but it still shows me the exception. What should I do?

**Comment by dereuromark** [comment]
This should easily be fixed by adding this into your app_queue config and making sure this file is loaded.
I bet yours isnt :)
You got a load call for this file?

But apart from this you are right: This shouldnt be a required param.
I fixed it in https://github.com/dereuromark/cakephp-queue/commit/da309c1527a1756c64c6bef1e82e18912c14c7ab for now.

**Comment by hectorviov** [comment]
I'm sorry, but I was having monday brain. The thing is I was testing it on a remote QA server and not on the localhost, didn't push the updates yet and I was going crazy. Sorry about that...
